# Generated by Django 4.0.4 on 2022-04-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.CharField(default='https://i.imgur.com/99v0yRs.jpg', max_length=100),
            preserve_default=False,
        ),
    ]
