# Generated by Django 4.0.4 on 2022-04-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_api', '0002_review_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='trip_end_date',
            field=models.DateField(default='2022-01-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='trip_start_date',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='img',
            field=models.CharField(default='https://i.imgur.com/99v0yRs.jpg', max_length=100),
        ),
    ]
