# Generated by Django 4.0.4 on 2022-04-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_api', '0003_review_trip_end_date_review_trip_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='trip_end_date',
            field=models.DateField(default='2022-01-05'),
        ),
        migrations.AlterField(
            model_name='review',
            name='trip_start_date',
            field=models.DateField(default='2022-01-01'),
        ),
    ]
