# Generated by Django 4.0.4 on 2022-04-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_api', '0004_alter_review_trip_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='test',
            field=models.CharField(default='hello', max_length=32),
            preserve_default=False,
        ),
    ]
