# Generated by Django 4.0.4 on 2022-04-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_api', '0005_review_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='test',
        ),
    ]
